### PR TITLE
feat(poem.txt): added ascii art

### PR DESCRIPTION
**Pull request by kalatkarin**
Added dreamcatcher ascii art!! :D

### CODE REVIEW

**Comment by maypotot** [comment]
Ano yan? HAGHAHGAHGAH WHAT IS THAT ASCII ART SUPPOSED TO BE WAGUAW

**Comment by maypotot** [comment]
It looks cute but I can't tell what it is

**Comment by maypotot** [comment]
AY OMG ITS A DREAMCATCHER AOGOAWHGOAHWOGH THATS SO KYUTTTTTTTT

**Comment by kalatkarin** [comment]
it's a dreamcatcher!! like the actual object ToT

**Comment by maypotot** [comment]
Approved.

**Pull request merged**
